# Generated by Django 3.1.1 on 2020-09-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('funcionarios', '0002_auto_20200922_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamentos',
            field=models.ManyToManyField(to='departamentos.Departamento'),
        ),
    ]
